# Generated by Django 4.2.16 on 2024-11-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='LocationName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
