# Generated by Django 4.2.16 on 2024-11-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0002_alter_location_locationname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('StationID', models.AutoField(primary_key=True, serialize=False)),
                ('StationName', models.CharField(max_length=200, unique=True)),
                ('isValid', models.BooleanField()),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.location')),
            ],
        ),
    ]
