# Generated by Django 4.2.16 on 2024-11-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0003_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('DataID', models.AutoField(primary_key=True, serialize=False)),
                ('DataTime', models.DateTimeField()),
                ('Value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('IndicatorID', models.AutoField(primary_key=True, serialize=False)),
                ('IndicatorName', models.CharField(max_length=200, unique=True)),
                ('Unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.role')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('RecordTime', models.DateTimeField()),
                ('DataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.data')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.user')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='IndicatorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.indicator'),
        ),
        migrations.AddField(
            model_name='data',
            name='StationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.station'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('AnalysisID', models.AutoField(primary_key=True, serialize=False)),
                ('ContaminationLevel', models.CharField(max_length=5)),
                ('AnalysisTime', models.DateTimeField()),
                ('AQI', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Advice', models.TextField()),
                ('StationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.station')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('AdviceID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('AdviceTime', models.DateTimeField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqt.user')),
            ],
        ),
    ]
