# Generated by Django 4.2.16 on 2024-11-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0004_data_indicator_role_user_record_data_indicatorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='LocationID',
            new_name='Locationi',
        ),
    ]
