# Generated by Django 4.2.16 on 2024-11-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0005_rename_locationid_station_locationi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='Locationi',
            new_name='LocationID',
        ),
    ]
