# Generated by Django 4.2.16 on 2024-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqt', '0006_rename_locationi_station_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='RoleID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
